

junit:
  stage: test
  script:
    - mvn -B clean test

generate_artifacts:
  stage: deploy
  script:
    - mvn -B clean site package



#junit:
#  stage: test
#  script:
#    - cd visualiser/
#    - mvn -B clean test
#
#generate_artifacts:
#  stage: deploy
#  script:
#    - cd visualiser/
#    - mvn -B clean site package